### PR TITLE
Add multipart support

### PR DESCRIPTION
**Pull request by nicklasaven**
Suggesting a multipart version of pgmail for html formatting, with plain text fallback.

### CODE REVIEW

**Comment by captbrando** [comment]
I like this. Let me review. This is a good way to add this functionality with backwards compatibility.

**Comment by nicklasaven** [comment]
I am not sure what is best to have many sql functions with few parameters or fewer with more parameters. It can get messy. I mean the multipart/alternate can be switched to multipart/mixed too. To have different content type at the same time. I have also added cc and bcc but I don't know the best way to implement that in a generic sql function without getting to many parameters. 

As long as your original function is untouched maybe a function with many options and named parameters would be ok? If most parametrs have default values and the user uses the syntax with named parameters they can use only the ones they want like:
SELECT pgMail_generic(from:='aaa@bbb.cc', to:='bbb@ccc.dd', cc:='ccc@ddd.ee', subject:='aa', message=:'test');

It gets quite verbose but then there can be flags about content type and maybe other stuff that can be ignored and following default values.

Or there van of course be many functions with overloading parameters. But hten the user must remember in what order the parameters come.

This was not a discusseion for the PR but I don't know where to put it.

pgMail is a great idea, thanks for it :-)
and it is so simplle and great so I guess users extend it themselves as they need but I think it would be great to put some more options in the project to make things easier.

**Comment by captbrando** [comment]
So TCL allows you to define an arbitrary number of arguments  in the procedure definition. Perhaps the right way to do this to not break anything is to use that and just add the multipart message as an argument. I'll look into this so that we maintain backwards compatibility without duplicating code.

**Comment by captbrando** [comment]
OK, I think I have a way to do this. But I have a question about MIME Multipart Messages. Would we ONLY use the MIME Multipart if the the HTML message is present? I'm thinking the logic would look like this:

# Set up the message
# After the Subject line, test to see if both HTML and Plain Text messages are present.
# If present, set up MIME Multipart.
# If not, just set up the appropriate MIME message (either plain text or HTML)
# Paste HTML if present
# Paste plain text if present
# Close out message.

do you agree? If so, I can modify the function using the default empty values such that it will be backwards compatible.

**Comment by captbrando** [comment]
Give this branch a shot and see if it is working for you. https://github.com/captbrando/pgMail/tree/mime_multipart

**Comment by nicklasaven** [comment]
I think the approach is good for plain and multipart. Maybe it would be interesting in the future to extend to attachments and maybe other things. But that will be another chapter of the story :-)

I haven't tested your code, but I think there is a problem on row 50 and 56. Shouldn't that be stand alone if -clauses? Now, if multipart only line 49 will be picked.

**Comment by captbrando** [comment]
dude. GOOD CALL. Just fixed that. I was coding a bit late and I'm under the weather. I need to build more tests for this! I was testing last night but working on the non-multipart logic. So I didn't come across this bug.

Check now and let me know your thoughts? This one looks right to me. If you agree, I'll merge and release.

**Comment by nicklasaven** [comment]
It looks good :-) I don't reach the smtp server now, but if it works for you it should be ok.

If you put names on the arguments it will be a little more verbose. It can be used without writing the variable name or variable_name:=value and then the order you give the arguments doesn't matter.
If so the function head would be something like:
create function pgmail(from text,to text,subject text,plain text,html text default '')

It is not important for me so go for which version you like :-)

Thanks for doing this!

Some day I will dive into the xml-functions for postgresql and see if it would be possible to build some simple framework for building emails like the example in the bottom of this :
https://www.postgresql.org/docs/10/static/functions-xml.html#FUNCTIONS-XML-MAPPING

**Pull request closed without merging**
